- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- README.md
- appveyor.yml
- xFailOverCluster.psd1
Releasing version 1.2.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/12)
> Release of version 1.2.0.0 of xFailOverCluster

- DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1
- Tests/MSFT_xClusterDisk.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/17)
> Fixed wrong variable name

- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- README.md
- appveyor.yml
- xFailOverCluster.psd1
Releasing version 1.6.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/31)
> Release of version 1.6.0.0 of xFailOverCluster

- DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1
- README.md
- Tests/MSFT_xClusterDisk.Tests.ps1
- Changes to xClusterPreferredOwner
- Script Analyzer warnings have been fixed (issue #50). This also failed the tests for the resource.
- Fixed test that was failing in  AppVeyor (issue #55).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/63)
> xFailOverCluster: Fixed failing tests in AppVeyor

- CHANGELOG.md
- README.md
- Changes to README.md
- Fixed CodeCov badge links so they now can be clicked on.
None
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/66)
> README.md: Fixed CodeCov badge links

- CHANGELOG.md
- README.md
- Added code block around types in README.md.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/89)
> README.md: Added code block around types in README.md

- CHANGELOG.md
Fix typos in CHANGELOG.md
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/123)
> xFailOverCluster: Fix typos in CHANGELOG.md

- CHANGELOG.md
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.schema.mof
- DSCResources/MSFT_xClusterNetwork/en-US/MSFT_xClusterNetwork.strings.psd1
- Changes to xClusterNetwork
- Enabled localization for all strings ([issue #85](https://github.com/PowerShell/xFailOverCluster/issues/85)).
- Fixed typo in parameter descriptions in comment-based help.
Fixes #85 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/116)
> xClusterNetwork: Enabled localization

- CHANGELOG.md
- DSCResources/CommonResourceHelper.psm1
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1
- DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1
- DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1
- Examples/Resources/xCluster/1-CreateFirstNodeOfAFailoverCluster.ps1
- Examples/Resources/xCluster/2-JoinAdditionalNodeToFailoverCluster.ps1
- Examples/Resources/xCluster/3-CreateFailoverClusterWithTwoNodes.ps1
- Examples/Resources/xClusterDisk/1-AddClusterDisk.ps1
- Examples/Resources/xClusterDisk/2-RemoveClusterDisk.ps1
- Examples/Resources/xClusterNetwork/1-ChangeClusterNetwork.ps1
- Examples/Resources/xClusterPreferredOwner/1-AddPreferredOwner.ps1
- Examples/Resources/xClusterPreferredOwner/2-RemovePreferredOwner.ps1
- Examples/Resources/xClusterQuorum/1-SetQuorumToNodeMajority.ps1
- Examples/Resources/xClusterQuorum/2-SetQuorumToNodeAndDiskMajority.ps1
- Examples/Resources/xClusterQuorum/3-SetQuorumToNodeAndFileShareMajority.ps1
- Examples/Resources/xClusterQuorum/4-SetQuorumToDiskOnly.ps1
- Examples/Resources/xWaitForCluster/1-WaitForFailoverClusterToBePresent.ps1
- Tests/TestHelpers/CommonTestHelper.psm1
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Tests/Unit/Stubs/Write-ModuleStubFile.ps1
- Minor style changes.
- Minor style changes.
- Changes to xClusterNetwork
- Minor style changes.
- Changes to xClusterPreferredOwner
- Minor style changes.
- Changes to xClusterQuorum
- Minor style changes.
- Changes to xWaitForCluster
- Minor style changes.
Fixes #135 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/136)
> xFailOverCluster: Minor style changes and applied auto-formatting

- CHANGELOG.md
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1
- DSCResources/MSFT_xClusterQuorum/en-US/MSFT_xClusterQuorum.strings.psd1
- Changes to xClusterQuorum
- Enabled localization for all strings (issue #87).
Fixes #87 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/138)
> xClusterQuorum: Enabled localization

- CHANGELOG.md
- README.md
**Update Readme for clarity on xClusterNetwork**
Update readme for clarity on adding / removing networks from failover clusters.
Closes #92 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/150)
> xClusterNetwork: Update readme

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/MSFT_xCluster.schema.mof
- Examples/Resources/xCluster/4-CreateFailoverClusterAndIgnoreANetwork.ps1
- README.md
- Tests/Unit/MSFT_xCluster.Tests.ps1
Creating PR early so people can see the progress and offer help/advice @johlju
Fixes #143
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/145)
> xCluster: Adding IgnoreNetwork Parameter

- CHANGELOG.md
- LICENSE
- xFailOverCluster.psd1
- Changes to xFailoverCluster
- Updated year to 2018 in license file and module manifest (issue #167).
Fixes #167 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/168)
> xFailoverCluster: Update manifest and license to reflect new year

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/MSFT_xCluster.schema.mof
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.schema.mof
- Examples/Resources/xCluster/2-JoinAdditionalNodeToFailoverCluster.ps1
- Examples/Resources/xCluster/4-CreateFailoverClusterAndIgnoreANetwork.ps1
- Examples/Resources/xCluster/4-CreateFirstNodeOfAFailoverClusterWithDHCP.ps1
- Examples/Resources/xCluster/5-JoinAdditionalNodeToFailoverClusterWithDHCP.ps1
- Examples/Resources/xClusterQuorum/5-SetQuorumToNodeAndCloudMajority.ps1
- LICENSE
- README.md
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Tests/Unit/MSFT_xClusterDisk.Tests.ps1
- Tests/Unit/MSFT_xClusterNetwork.Tests.ps1
- Tests/Unit/MSFT_xClusterPreferredOwner.Tests.ps1
- Tests/Unit/MSFT_xClusterQuorum.Tests.ps1
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- xFailOverCluster.psd1
Releasing version 1.9.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/174)
> Release of version 1.9.0.0 of xFailOverCluster

- CHANGELOG.md
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1
- DSCResources/MSFT_xClusterProperty/MSFT_xClusterProperty.psm1
- DSCResources/MSFT_xClusterProperty/MSFT_xClusterProperty.schema.mof
- DSCResources/MSFT_xClusterProperty/en-US/MSFT_xClusterProperty.strings.psd1
- Examples/Resources/xClusterProperty/1-SetClusterProperties.ps1
- README.md
- Tests/Unit/MSFT_xClusterNetwork.Tests.ps1
- Tests/Unit/MSFT_xClusterProperty.Tests.ps1
- xFailOverCluster.psd1
Releasing version 1.10.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/179)
> Release of version 1.10.0.0 of xFailOverCluster

- .gitattributes
- .vscode/settings.json
- CHANGELOG.md
- appveyor.yml
* Update appveyor.yml to use the default template.
* Added default template files .codecov.yml, .gitattributes, and .gitignore, and .vscode folder.
n/a
Entry should say what was changed, and how that affects users (if applicable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/187)
> Update to use template files

- CHANGELOG.md
- xFailOverCluster.psd1
Releasing version 1.12.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/198)
> Release of version 1.12.0.0 of xFailOverCluster

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/en-US/MSFT_xCluster.strings.psd1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- xFailOverCluster.psd1
Releasing version 1.13.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/204)
> Release of version 1.13.0.0 of xFailOverCluster

- CHANGELOG.md
- azure-pipelines.yml
- source/Modules/CommonResourceHelper/CommonResourceHelper.psd1
- source/Modules/CommonResourceHelper/CommonResourceHelper.psm1
- tests/Unit/CommonResourceHelper.Tests.ps1
- CommonResourceHelper
- Fix unit tests to load the helper modules using module manifest.
- Fix to correctly export the functions in the helper module
([issue #214](https://github.com/dsccommunity/xFailOverCluster/issues/214)).
- Fix typo in module manifest.
- Fixes #214 
Entry should say what was changed, and how that affects users (if applicable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/215)
> Fix to correctly export the functions in the helper module

- CHANGELOG.md
- tests/Unit/MSFT_xCluster.Tests.ps1
- tests/Unit/MSFT_xClusterDisk.Tests.ps1
- tests/Unit/MSFT_xClusterNetwork.Tests.ps1
- tests/Unit/MSFT_xClusterPreferredOwner.Tests.ps1
- tests/Unit/MSFT_xClusterProperty.Tests.ps1
- tests/Unit/MSFT_xClusterQuorum.Tests.ps1
- tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Changed unit tests to handle missing DscResource.Test better.
None
Entry should say what was changed, and how that affects users (if applicable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/217)
> xFailOverCluster: Changed unit tests to handle missing DscResource.Test better

- CHANGELOG.md
- source/xFailOverCluster.psd1
- Update module manifest exporting resources
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/221)
> Update module manifest exporting resources

- CHANGELOG.md
- azure-pipelines.yml
- Set a display name on all the jobs and tasks in the CI pipeline.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/225)
> xFailOverCluster: Set display names in the CI pipeline

- CHANGELOG.md
- GitVersion.yml
- azure-pipelines.yml
- Update GitVersion.yml with the correct regular expression
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/226)
> Update GitVersion.yml with the correct regular expression

- CHANGELOG.md
- tests/Unit/MSFT_xCluster.Tests.ps1
- tests/Unit/MSFT_xClusterDisk.Tests.ps1
- tests/Unit/MSFT_xClusterNetwork.Tests.ps1
- tests/Unit/MSFT_xClusterPreferredOwner.Tests.ps1
- tests/Unit/MSFT_xClusterProperty.Tests.ps1
- tests/Unit/MSFT_xClusterQuorum.Tests.ps1
- tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Fix import statement in all tests, making sure it throws if module
DscResource.Test cannot be imported.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/228)
> Fix import statement in all tests

- CHANGELOG.md
- azure-pipelines.yml
- Update the deploy step so that it skips deploy on merge to forks.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/230)
> Update the deploy step

- CHANGELOG.md
- azure-pipelines.yml
- Update the deploy stage so that it is skipped when merging
branch master in forks.
part of issue #231 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/232)
> xFailOverCluster: Update the deploy stage

- .codecov.yml
- CHANGELOG.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/224)
> Adding back publishing code coverage to Codecov.io

- CHANGELOG.md
- README.md
- Add status badge for Codecov.io in README.md.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/235)
> Add status badge for Codecov.io in README.md

- CHANGELOG.md
- azure-pipelines.yml
- Changed integration tests to run on a a build image with Windows Server
2019 since the one we previously used was removed from Azure Pipelines.
- Fixes #233 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/239)
> xFailOverCluster: Integration tests runs on Windows 2019

- CHANGELOG.md
- azure-pipelines.yml
- Only run the CI pipeline on branch `master` when there are changes to
inside the `source` folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/240)
> xFailOverCluster: Update CI paths trigger

- CHANGELOG.md
- azure-pipelines.yml
- Updated CI pipeline to get version from the property `NuGetVersionV2`.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/241)
> xFailOverCluster: Updated CI pipeline

- .github/CONTRIBUTING.md
- CHANGELOG.md
- GitVersion.yml
- README.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
- source/Examples/Resources/xCluster/1-xCluster_CreateFirstNodeOfAFailoverClusterConfig.ps1
- source/Examples/Resources/xCluster/2-xCluster_JoinAdditionalNodeToFailoverClusterConfig.ps1
- source/Examples/Resources/xCluster/3-xCluster_CreateFailoverClusterWithTwoNodesConfig.ps1
- source/Examples/Resources/xCluster/4-xCluster_CreateFailoverClusterAndIgnoreANetworkConfig.ps1
- source/Examples/Resources/xCluster/5-xCluster_CreateFirstNodeOfAFailoverClusterWithDHCPConfig.ps1
- source/Examples/Resources/xCluster/6-xCluster_JoinAdditionalNodeToFailoverClusterWithDHCPConfig.ps1
- source/Examples/Resources/xClusterDisk/1-xClusterDisk_AddClusterDiskConfig.ps1
- source/Examples/Resources/xClusterDisk/2-xClusterDisk_RemoveClusterDiskConfig.ps1
- source/Examples/Resources/xClusterNetwork/1-xClusterNetwork_ChangeClusterNetworkConfig.ps1
- source/Examples/Resources/xClusterPreferredOwner/1-xClusterPreferredOwner_AddPreferredOwnerConfig.ps1
- source/Examples/Resources/xClusterPreferredOwner/2-xClusterPreferredOwner_RemovePreferredOwnerConfig.ps1
- source/Examples/Resources/xClusterProperty/1-xClusterProperty_SetClusterPropertiesConfig.ps1
- source/Examples/Resources/xClusterQuorum/1-xClusterQuorum_SetQuorumToNodeMajorityConfig.ps1
- source/Examples/Resources/xClusterQuorum/2-xClusterQuorum_SetQuorumToNodeAndDiskMajorityConfig.ps1
- source/Examples/Resources/xClusterQuorum/3-xClusterQuorum_SetQuorumToNodeAndFileShareMajorityConfig.ps1
- source/Examples/Resources/xClusterQuorum/4-xClusterQuorum_SetQuorumToDiskOnlyConfig.ps1
- source/Examples/Resources/xClusterQuorum/5-xClusterQuorum_SetQuorumToNodeAndCloudMajorityConfig.ps1
- source/Examples/Resources/xWaitForCluster/1-xWaitForCluster_WaitForFailoverClusterToBePresentConfig.ps1
- source/xFailOverCluster.psd1
- Renamed `master` branch to `main` (issue #246).
- Fixes #246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/247)
> xFailOverCluster: Updated pipeline files to support change of master to main

- CHANGELOG.md
- GitVersion.yml
- The component `gitversion` that is used in the pipeline was wrongly configured
when the repository moved to the new default branch `main`. It no longer throws
an error when using newer versions of GitVersion.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/250)
> xFailOverCluster: Fix GitVersion

- CHANGELOG.md
- README.md
- source/DSCResources/MSFT_xClusterProperty/MSFT_xClusterProperty.psm1
- source/DSCResources/MSFT_xClusterProperty/MSFT_xClusterProperty.schema.mof
- tests/Unit/MSFT_xClusterProperty.Tests.ps1
Added BlockCacheSize property to xClusterProperty
- Fixes #252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253)
> xClusterProperty: Add BlockCacheSize property -- Fix for issue #252

- CHANGELOG.md
- RequiredModules.psd1
- build.yaml
- Update pipeline to use new deploy tasks.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/254)
> xFailOverCluster: Update pipeline to use new deploy tasks

- CHANGELOG.md
- azure-pipelines.yml
- Deprecating xFailOverCluster before rename
In preparation for issue #69.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/265)
> Deprecating xFailOverCluster before rename

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/274)
> Fix pull request template

- CHANGELOG.md
- azure-pipelines.yml
- FailoverClusterDsc
- Switch build pipeline to use `windows-latest` as the build agent.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/FailoverClusterDsc/285)
> Update build pipeline to use `windows-latest`

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .vscode/analyzersettings.psd1
- .vscode/extensions.json
- .vscode/settings.json
- CHANGELOG.md
- RequiredModules.psd1
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- SECURITY.md
- azure-pipelines.yml
- build.ps1
- build.yaml
Update module files to latest community versions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/FailoverClusterDsc/286)
> Update module files

- CHANGELOG.md
- azure-pipelines.yml
Use CodeCov CLI
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/FailoverClusterDsc/287)
> Use CodeCov CLI

- CHANGELOG.md
- azure-pipelines.yml
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/FailoverClusterDsc/288)
> Add CodeCov token

- CHANGELOG.md
- azure-pipelines.yml
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/FailoverClusterDsc/289)
> Update CodeCov Command
