dsccommunity/FailoverClusterDsc

- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- README.md
Added the '-NoStorage' switch to ensure that disks do not automatically get added to the cluster when adding nodes.
> Added '-NoStorage' to add-clusternode cmdlet - fixed issue #4

- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
If during the 'Set-TargetResource' a new cluster is being created, but the 'New-Cluster' command does not end successfully. Then the 'while' loop was running forever keeping the LCM in a busy state.
I noticed the problem when creating a cluster but the CNO already existed in AD and was linked to a previously created cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/30)
> Removed endless while loop

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
- Added 'Code of Conduct' text to the README.md (issue #44).
- Added TOC for all resources in the README.md (issue #43).
- Fixed typos and lint errors in README.md.
- Fixed style issue in example in README.md.
- Removed 'Unreleased' "tag" from the resources xClusterQuorum and xClusterDisk (issue #36)
- Added new sections to each resource (Requirements, Parameters and Examples) in the README.md. Some does not yet have any examples, so they are set to 'None.'.
- Added GitHub templates PULL\_REQUEST\_TEMPLATE, ISSUE_TEMPLATE and CONTRIBUTING.md (issue #45).
- Split the change log from README.md to a seperate file CHANGELOG.md (issue #48).
- Added the resource xClusterPreferredOwner to README.md (issue #51).
- Added the resource xClusterNetwork to README.md …
> xFailOverCluster: Updating README.md, adding CHANGELOG.md, adding GitHub templates

- .gitignore
- .vscode/settings.json
- CHANGELOG.md
- Added VS Code workspace settings file with formatting settings matching the
Style Guideline (issue #67). That will make it possible inside VS Code to
press SHIFT+ALT+F, or press F1 and choose 'Format document' in the list. The
PowerShell code will then be formatted according to the Style Guideline
(although maybe not complete, but would help a long way).
Fixes #67 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/68)
> xFailOverCluster: Added VS Code workspace settings file

- CHANGELOG.md
- DSCResources/CommonResourceHelper.psm1
- DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1
- DSCResources/MSFT_xClusterDisk/en-US/MSFT_xClusterDisk.strings.psd1
- README.md
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Added a common resource helper module with helper functions for localization.
- Added helper functions; Get-LocalizedData, New-InvalidResultException, New-ObjectNotFoundException, InvalidOperationException and InvalidArgumentException.
- Fixed lint error MD034 and fixed typos in README.md.
- Enabled localization for all strings (issue #84).
- Changes to xClusterPreferredOwner
- Replace an URL which describes more generic the Role setting for xClusterNetwork.
Fixes #84 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xf …
> xFailOverCluster: Localization support, localized strings in xClusterDisk and some cleanup.

- CHANGELOG.md
- DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1
- Fixed a data type that was not fully qualified.
Missed this when trying to align this resource against the style guideline. 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/112)
> xClusterDisk: Fixed a data type that was not fully qualified

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Resolved Script Analyzer rule warnings by changing Get-WmiObject to Get-CimInstance (issue #49).
Fixes #49 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/110)
> xCluster: Fixed PSSA rule warnings

- .MetaTestOptIn.json
- CHANGELOG.md
- DSCResources/CommonResourceHelper.psm1
- Tests/Unit/Stubs/FailoverClusters.stubs.psm1
- Opt-in for module files common tests (issue #119).
- Removed Byte Order Mark (BOM) from the files; CommonResourceHelper.psm1 and FailoverClusters.stubs.psm1.
Fixes #119
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/120)
> xFailOverCluster: Opt-in for module files common tests

- CHANGELOG.md
- DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1
- DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.schema.mof
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Changes to xWaitForCluster
- Refactored the unit test for this resource to use stubs and increase coverage
(issue #78).
- Now the Test-TargetResource correctly returns false if the domain namn cannot
be evaluated  (issue #107).
- Changed the code to be more aligned with the style guideline.
- Updated parameter description in the schema.mof.
- Resolved Script Analyzer warnings (issue #54).
Fixes #78 
Fixes #107 
Fixes #54 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/108)
> xWaitForCluster: Added unit test

- .MetaTestOptIn.json
- CHANGELOG.md
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Tests/Unit/MSFT_xClusterDisk.Tests.ps1
- Tests/Unit/MSFT_xClusterPreferredOwner.Tests.ps1
- Opt-in for script files common tests (issue #121).
- Removed Byte Order Mark (BOM) from the files; CommonResourceHelper.Tests.ps1,
MSFT\_xCluster.Tests.ps1, MSFT\_xClusterDisk.Tests.ps1,
MSFT\_xClusterPreferredOwner.Tests.ps1.
Fixes #121 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/122)
> xFailOverCluster: Opt-in for script files common tests

- CHANGELOG.md
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Changes to xFailoverCluster
- Removed Byte Order Mark (BOM) from the file; MSFT_xWaitForCluster.Tests.ps1.
For some reason the tests did not fail on this in the PR. But failed after merge, when the dev branch was tested. :/
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/130)
> xFailoverCluster: Removed Byte Order Mark (BOM) from script file

- CHANGELOG.md
- DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.psm1
- DSCResources/MSFT_xClusterPreferredOwner/en-US/MSFT_xClusterPreferredOwner.strings.psd1
- Changes to xClusterPreferredOwner
- Enabled localization for all strings ([issue #86](https://github.com/PowerShell/xFailOverCluster/issues/86)).
- Fixed typo in the returned hash table from Get-TargetResource.
Fixes #86 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/117)
> xClusterPreferredOwner: Enabled localization

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/en-US/MSFT_xCluster.strings.psd1
- Tests/TestHelpers/CommonTestHelper.psm1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Added common test helper functions to help test the throwing of localized error strings.
- Get-InvalidArgumentRecord
- Get-InvalidOperationRecord
- Get-ObjectNotFoundException
- Get-InvalidResultException.
- Enabled localization for all strings (issue #83).
- Added tests to improve code coverage.
Fixes #83 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/118)
> xCluster: Enabled localization

- CHANGELOG.md
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Fixed random problem with tests failing with error "Invalid token for
impersonation - it cannot be duplicated." (issue #133).
Fixes #133 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/134)
> xCluster: Fixed random problem with tests failing

- CHANGELOG.md
- LICENSE
- xFailOverCluster.psd1
- Updated year to 2017 in license file and module manifest (issue #131).
Fixes #131 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/132)
> xFailOverCluster: Updated year to 2017 in license file and module manifest

- CHANGELOG.md
- DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.psm1
- DSCResources/MSFT_xWaitForCluster/en-US/MSFT_xWaitForCluster.strings.psd1
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Changes to xWaitForCluster
- Enabled localization for all strings (issue #88).
Fixes #88 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/139)
> xWaitForCluster: Enabled localization

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/en-US/MSFT_xCluster.strings.psd1
- DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.psm1
- DSCResources/MSFT_xClusterDisk/en-US/MSFT_xClusterDisk.strings.psd1
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1
- DSCResources/MSFT_xClusterNetwork/en-US/MSFT_xClusterNetwork.strings.psd1
- Fixed Script Analyzer warnings for Write-Verbose.
- Fixed Script Analyzer warnings for Write-Verbose.
- Changes to xClusterNetwork
- Fixed Script Analyzer warnings for Write-Verbose.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/137)
> xFailOverCluster: Fixed Script Analyzer warnings for Write-Verbose

- CHANGELOG.md
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Tests/Unit/MSFT_xClusterDisk.Tests.ps1
- Tests/Unit/MSFT_xClusterNetwork.Tests.ps1
- Tests/Unit/MSFT_xClusterPreferredOwner.Tests.ps1
- Tests/Unit/MSFT_xClusterQuorum.Tests.ps1
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
Update Pester syntax to v4 flags
Resolves #149
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/152)
> xFailOverCluster: Update Pester syntax to v4

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/MSFT_xCluster.schema.mof
- Examples/Resources/xCluster/1-CreateFirstNodeOfAFailoverCluster.ps1
- Examples/Resources/xCluster/2-JoinAdditionalNodeToFailoverCluster.ps1
- Examples/Resources/xCluster/4-CreateFirstNodeOfAFailoverClusterWithDHCP.ps1
- Examples/Resources/xCluster/5-JoinAdditionalNodeToFailoverClusterWithDHCP.ps1
- README.md
- Tests/Unit/CommonResourceHelper.Tests.ps1
- Tests/Unit/MSFT_xCluster.Tests.ps1
- Tests/Unit/MSFT_xWaitForCluster.Tests.ps1
- Allow cluster to be assigned IP address from a DHCP (issue #109).
When parameter StaticIPAddress is not specified then cluster will be configured
to use IP address from a DHCP.
Fixes #109 
Fixes #28 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/113)
> xCluster: Allow cluster to be assigned IP address from a DHCP

- README.md
- This fixes the type qualifier for parameter StaticIPAddress that was recently merged.
***Note:** Skipping CHANGELOG.md for this since there are already an entry for this in the Unreleased section.*
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/165)
> xCluster: Fix parameter type qualifier

- CHANGELOG.md
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1
- README.md
- Tests/Unit/MSFT_xClusterQuorum.Tests.ps1
- Changes to xClusterQuorum
- When using NodeAndFileShareMajority on Windows Server 2016 any subsequent run
failed when Test-TargetResource validated the configuration.
Fixes #35
**Task list:**
Previous PR-> https://github.com/PowerShell/xFailOverCluster/pull/141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/144)
> xClusterQuorum: Fixed the filesharewitness checks

- CHANGELOG.md
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.psm1
- DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.schema.mof
- Examples/Resources/xClusterQuorum/5-SetQuorumToNodeAndCloudMajority.ps1
- README.md
- Tests/Unit/MSFT_xClusterQuorum.Tests.ps1
Added possibility to use a "cloud witness", i.e. an Azure storage account, for a Windows 2016 cluster.
Based on documentation: https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness
The storage account name is provided through the existing parameter "Resource".
An additional (optional) parameter has been created for the storage account key.
The standard endpoint (.blob.core.microsoft.net) is used. This parameter cannot be overriden in this release.
Fixes: #37 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/153)
> xClusterQuorum: Added cloud witness functionality on Windows 2016

- CHANGELOG.md
- DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.psm1
- DSCResources/MSFT_xClusterNetwork/en-US/MSFT_xClusterNetwork.strings.psd1
- Tests/Unit/MSFT_xClusterNetwork.Tests.ps1
Convert the network role to the enum value if it returns a stirng, e.g. on WS2016.
Fixes #175 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/176)
> xClusterNetwork: Fix Role property never in desired state

- CHANGELOG.md
- DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- DSCResources/MSFT_xCluster/en-US/MSFT_xCluster.strings.psd1
- Tests/Unit/MSFT_xCluster.Tests.ps1
Updated the cluster membership check to return true if the node is paused.  Added a localized string/verbose message to state the node is 'Paused' during the test method.
Fixes #201 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xfailovercluster/202)
> xCluster - Update Cluster check to account for Paused Nodes

- CHANGELOG.md
- azure-pipelines.yml
-  Fix Azure Pipelines code coverage (issue #236).
- Fixes #236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/237)
> Fix Azure Pipelines code coverage

- CHANGELOG.md
- azure-pipelines.yml
- Only run CI pipeline on branch `master` when there are changes to files
inside the `source` folder.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/238)
> xFailOverCluster: CI pipeline runs on changes in source folder

- CHANGELOG.md
- RequiredModules.psd1
- build.yaml
- tests/Unit/MSFT_xCluster.Tests.ps1
- Pin Pester to 4.10.1 in `RequiredModule.psd1` since the tests does
not support Pester 5.
- Updated repository to use the latest version of the module ModuleBuilder.
- xCluster
- Fixed Describe-block descriptions (issue #234).
- Fixes #234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/242)
> xCluster: Fix Describe-block descriptions

- CHANGELOG.md
- README.md
- source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1
- source/DSCResources/MSFT_xCluster/MSFT_xCluster.schema.mof
- tests/Unit/MSFT_xCluster.Tests.ps1
This PR makes the DomainAdministratorCredential parameter optional for xCluster. 
In order to fulfill the use-case where Cluster Name Objects are prestaged in Active Directory 
prior to cluster creation as per [microsoft docs](https://docs.microsoft.com/en-us/windows-server/failover-clustering/prestage-cluster-adds). 
- Fixes  #164 
- Fixes #70 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249)
> xCluster: Make DomainAdministratorCredential optional

- CHANGELOG.md
- README.md
- source/DSCResources/DSC_Cluster/DSC_Cluster.psm1
- source/DSCResources/DSC_Cluster/DSC_Cluster.schema.mof
- source/DSCResources/DSC_Cluster/en-US/DSC_Cluster.strings.psd1
- source/Examples/Resources/Cluster/7-Cluster_JoinAdditionalNodeToFailoverClusterConfigAndDontEvictDownedNodes.ps1
- tests/Unit/DSC_Cluster.Tests.ps1
Parameter `KeepDownedNodesInCluster` will control removing nodes in a down state. Defaulting to `false` current behavior is kept and nodes in a downed state will be evicted. When set to `true`, nodes in a down state will not be evicted.
- Fixes #257 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/272)
> Cluster: Adding parameter KeepDownedNodesInCluster to control whether or not to remove nodes in downed state

- CHANGELOG.md
- source/FailoverClusterDsc.psd1
- URLs in module manifest now points to the renamed repository.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/277)
> Update URLs in module manifest
